# Generated by Django 5.1.1 on 2024-10-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_admin_category_customer_alter_product_image_cart_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("image", models.ImageField(upload_to="static/image")),
                ("brand", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="cart",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.products"
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.products"
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
