# Generated by Django 5.1.1 on 2024-11-07 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_delete_category_remove_customer_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.products"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
