# Generated by Django 5.1.1 on 2024-11-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_order_payment_method_order_shipping_address_cartitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.BigIntegerField(),
        ),
    ]
