# Generated by Django 5.1.1 on 2024-11-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="txn_ref",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
